name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-pythonapp:${{ github.run_number }}

    - name: Tag the Docker image
      run: docker tag my-pythonapp:${{ github.run_number }} hassanb111/my-pythonapp:${{ github.run_number }}

    - name: Push the Docker image
      run: docker push my-dockerhub-username/my-pythonapp:${{ github.run_number }}
